### ISSUE TITLE
custom step count for each motor.

### ISSUE THREAD

**Issue by i-make-robots** [MarginallyClever/Makelangelo-firmware#101]
**Is your feature request related to a problem? Please describe.**
Can't set different step/gear ratio for each motor

**Describe the solution you'd like**
config defines would be enough.

**Describe alternatives you've considered**

**Additional context**
Marlin already has good examples of this.  read how they do it and follow along.

**Comment by cad435** [comment]
this is aleady done for the sixi in robot_sixi.h I guess?
