### ISSUE TITLE
Flag "-DUSE_ALT_SERVO" not set for ramps and sixi enviroment in PlatformIO.ini

### ISSUE THREAD

**Issue by cad435** [MarginallyClever/Makelangelo-firmware#108]
On both [env:]'s the build flags should have -DUSE_ALT_SERVO attached to its argument list.

![image](https://user-images.githubusercontent.com/16453385/106598268-cf55d100-6557-11eb-8e9a-d635f84b3602.png)

**Comment by i-make-robots** [comment]
fixed in 481d801
