### ISSUE TITLE
pin number for motor_3_enable_pin and motor_4_enable_pin are reversed

### ISSUE THREAD

**Issue by jportway** [MarginallyClever/Makelangelo-firmware#18]
Hi,
The pin numbers in configure.h for these extra motors have been swapped when compared with the rumba board documentation.

motor 3 should be 24
motor 4 should be 27

**Comment by i-make-robots** [comment]
Thanks!  I never noticed because the Makelangelo only uses two motors.  I've swapped them in my local copy.
