### ISSUE TITLE
Add menu to draw common paper boundaries 

### ISSUE THREAD

**Issue by i-make-robots** [MarginallyClever/Makelangelo-firmware#25]
assumes starting at home position.
A0...A4?
portrait and landscape?

**Comment by halfluck** [comment]
+1 this would be fantastic!

**Comment by i-make-robots** [comment]
@halfluck I think instead of in the calibration menu it'll be a generator and it will work with whatever paper size is currently set.  That way it will draw the correct border no matter the paper size.

**Comment by i-make-robots** [comment]
Ugh, I thought this was in Makelangelo-software.  coffee wasn't kicking in yet.

**Comment by halfluck** [comment]
Yes coffee is a very important part of the process :) ==> [https://imgur.com/23kgyYg](url)
I use the Boundary on Makeangelo Software, First I set the page size to A3 etc then do a boundry
so I know exactly where to stick the paper.

**Comment by i-make-robots** [comment]
DUDE.  That was great.  tag me in more of these.  I want to share sweet sweet drawings people do.

**Comment by i-make-robots** [comment]
committed an implementation in dbee104

**Comment by halfluck** [comment]
Hi Dan,

I can confirm this border feature is working!

Cheers Rob.
