### ISSUE TITLE
Error compiling for board Arduino/Genuino Mega or Mega 2560.

### ISSUE THREAD

**Issue by Shahriar57** [MarginallyClever/Makelangelo-firmware#32]
i can not upload firmware to 2560 . 
error it shows in IDE
exit status 1

In file included from D:\3dp\POLAR DRAWBOT\Firmware\Makelangelo-firmware\Makelangelo-firmware\Makelangelo-firmware.ino:12:0:

sketch\configure.h:37:30: fatal error: robot_polargraph.h: No such file or directory

 #include "robot_polargraph.h"

                              ^

compilation terminated.

exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.

**Comment by i-make-robots** [comment]
You have deleted that file accidentally.  Download it again.
