### ISSUE TITLE
LCD Drive feedrate not working as expected

### ISSUE THREAD

**Issue by hazcat** [MarginallyClever/Makelangelo-firmware#46]
The LCD DriveFeedrate command sets the feedrate to 100 after any input is received.

This is due to an operator precedence issue:
float newF = feed_rate + lcd_turn > 0 ? 1 : -1;
the addition operator has precedence over the relational operator which means the above line is equivalent to:
float newF = (feed_rate + lcd_turn) > 0 ? 1 : -1;

**Comment by i-make-robots** [comment]
Whoops.  Good catch!  Send a pull request, please?
