### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by devburke** [MarginallyClever/Makelangelo-firmware#6]
So for reasons that don't matter, I had to start fresh with installing the firmware, without access to my old copy. I can't seem to get it to compile now.

At first, I'm getting the error that it can't find the Adafruit_MotorShield files. Then when I copy those into the library (out of the firmware_ams folder), I get this error:

`sketch/Adafruit_MotorShield/utility/Adafruit_PWMServoDriver.cpp:18:37: fatal error: Adafruit_PWMServoDriver.h: No such file or directory
 #include <Adafruit_PWMServoDriver.h>
                                     ^
compilation terminated.
exit status 1
Error compiling for board Arduino/Genuino `Uno.``

But running the MotorParty example file in the motor shield library works just fine.

Any advice?

**Comment by i-make-robots** [comment]
You should not have to move the libraries anywhere with the latest Arduino.

On Sat, May 21, 2016 at 3:26 PM, Devin Burke <notifications@github.com>
wrote:

> So for reasons that don't matter, I had to start fresh with installing the
> firmware, without access to my old copy. I can't seem to get it to compile
> now.
>
> At first, I'm getting the error that it can't find the
> Adafruit_MotorShield files. Then when I copy those into the library (out of
> the firmware_ams folder), I get this error:
>
> sketch/Adafruit_MotorShield/utility/Adafruit_PWMServoDriver.cpp:18:37:
> fatal error: Adafruit_PWMServoDriver.h: No such file or directory
> #include <Adafruit_PWMServoDriver.h>
> ^
> compilation terminated.
> exit status 1
> Error compiling for board Arduino/GenuinoUno.``
>
> But running the MotorParty example file in the motor shield library works
> just fine.
>
> Any advice?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MarginallyClever/Makelangelo-firmware/issues/6>
>



-- 
Dan Royer, Owner, Marginally Clever Robots
<https://www.marginallyclever.com/>
Ph: +1 (604) 259-9564
Mo: +1 (604) 916-2281

**Comment by devburke** [comment]
If I don’t, I get this error:

/Users/Devin/Documents/Arduino/firmware_ams/firmware_ams.ino:133:34: fatal error: Adafruit_MotorShield.h: No such file or directory
 #include <Adafruit_MotorShield.h>
                                  ^
compilation terminated.
exit status 1
Error compiling for board Arduino/Genuino Uno.

**Comment by i-make-robots** [comment]
Try changing #include <Adafruit_PWMServoDriver.h> to #include
"Adafruit_PWMServoDriver.h".  they're in the same directory.

On Sat, May 21, 2016 at 3:42 PM, Devin Burke <notifications@github.com>
wrote:

> If I don’t, I get this error:
>
> /Users/Devin/Documents/Arduino/firmware_ams/firmware_ams.ino:133:34: fatal
> error: Adafruit_MotorShield.h: No such file or directory
> #include <Adafruit_MotorShield.h>
> ^
> compilation terminated.
> exit status 1
> Error compiling for board Arduino/Genuino Uno.
>
>
>
>
> > On May 21, 2016, at 5:33 PM, Dan Royer <notifications@github.com> wrote:
> >
> > You should not have to move the libraries anywhere with the latest
> Arduino.
> >
> > On Sat, May 21, 2016 at 3:26 PM, Devin Burke <notifications@github.com>
> > wrote:
> >
> > > So for reasons that don't matter, I had to start fresh with installing
> the
> > > firmware, without access to my old copy. I can't seem to get it to
> compile
> > > now.
> > >
> > > At first, I'm getting the error that it can't find the
> > > Adafruit_MotorShield files. Then when I copy those into the library
> (out of
> > > the firmware_ams folder), I get this error:
> > >
> > > sketch/Adafruit_MotorShield/utility/Adafruit_PWMServoDriver.cpp:18:37:
> > > fatal error: Adafruit_PWMServoDriver.h: No such file or directory
> > > #include <Adafruit_PWMServoDriver.h>
> > > ^
> > > compilation terminated.
> > > exit status 1
> > > Error compiling for board Arduino/GenuinoUno.``
> > >
> > > But running the MotorParty example file in the motor shield library
> works
> > > just fine.
> > >
> > > Any advice?
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/MarginallyClever/Makelangelo-firmware/issues/6>
> > >
> >
> >
> >
> > --
> > Dan Royer, Owner, Marginally Clever Robots
> > <https://www.marginallyclever.com/>
> > Ph: +1 (604) 259-9564
> > Mo: +1 (604) 916-2281
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub <
> https://github.com/MarginallyClever/Makelangelo-firmware/issues/6#issuecomment-220803902
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/MarginallyClever/Makelangelo-firmware/issues/6#issuecomment-220804232>
>



-- 
Dan Royer, Owner, Marginally Clever Robots
<https://www.marginallyclever.com/>
Ph: +1 (604) 259-9564
Mo: +1 (604) 916-2281

**Comment by devburke** [comment]
Got it working. Just had to restart the IDE to load the libraries. D’oh!

I finally got my DIY Makelangelo up and running. I’m moving the gondola around the page now though, and it’s moving very slow. I’ve tried changing acceleration from 20 to 100, changing the speed from 7500 to 20000, and same with the feed rate. All at the same time. Still moves at a snail’s pace. I’m still looking into why this could be.
