### ISSUE TITLE
Nema 17 stepper motor not rotating properly

### ISSUE THREAD

**Issue by IDmedia** [MarginallyClever/Makelangelo-firmware#7]
I've connected two Nema 17 motors from Adafruit to my Arduino and loaded up the firmware. Now I have a working servo, but only one of the stepper motors is rotating properly. The other (connected to M1/M2) only vibrates. I've tested both steppers so I know they work... Do I have to change anything in the firmware or what could cause the motor to not rotate correctly? The cable pairs should be correct as well. I'm powering the circuit using a 12V/2A power supply.

http://i.imgur.com/2RUh0yL.jpg

**Edit:** Measuring the voltage across GND and the different stepper pins I get 0.129V on all except M1... Does that mean my motor shield is broken or is there anything in the firmware that could cause this? I can't seem to find any references to it except from M1_PIN and M2_PIN.

**Comment by i-make-robots** [comment]
If it only vibrates it either doesn't have enough power or one of the wires
pairs is backwards (so one coil in the stepper fights the other coil)

On Sun, May 29, 2016 at 4:21 AM, IDmedia <notifications@github.com> wrote:

> I've connected two Nema 17 motors from Adafruit to my Arduino and loaded
> up the firmware. Now I have a working servo, but only one of the stepper
> motors is rotating properly. The other (connected to M1/M2) only vibrates.
> I've tested both steppers so I know they work... Do I have to change
> anything in the firmware or what could cause the motor to not rotate
> correctly? The cable pairs should be correct as well. I'm powering the
> circuit using a 12V/2A power supply.
>
> http://i.imgur.com/2RUh0yL.jpg
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MarginallyClever/Makelangelo-firmware/issues/7>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABZYhgypjppunjwbZQ42QQ__SgnxVCYrks5qGXamgaJpZM4IpRMs>
> .
>



-- 
Dan Royer, Owner, Marginally Clever Robots
<https://www.marginallyclever.com/>
Ph: +1 (604) 259-9564
Mo: +1 (604) 916-2281

**Comment by IDmedia** [comment]
I finally figured it out! Looks like the shield(s) I brought from eBay aren't good at all. There's a short between these two pins: http://i.imgur.com/O28CkQx.jpg

I'll try to get my hands on a second motor shield and give it another try. I'm also a bit worried about the heat it generates... maybe it's a better idea to get the new Adafruit Motor shield v 2.3?

**Comment by i-make-robots** [comment]
You might be able to scratch the board to break the short.
We only support the AMS 1.

Will you be contributing software patches?  Then you'd be safer taking the
2.3.

On Sun, May 29, 2016 at 2:40 PM, IDmedia <notifications@github.com> wrote:

> I finally figured it out! Looks like the shield(s) I brought from eBay
> aren't good at all. There's a short between these two pins:
> http://i.imgur.com/O28CkQx.jpg
>
> I'll try to get my hands on a second motor shield and give it another try.
> I'm also a bit worried about the heat it generates... maybe it's a better
> idea to get the new Adafruit Motor shield v 2.3?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/MarginallyClever/Makelangelo-firmware/issues/7#issuecomment-222384443>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABZYhkANk-23mmBQdzZDIlo3MuUBQIQ9ks5qGgfTgaJpZM4IpRMs>
> .
>



-- 
Dan Royer, Owner, Marginally Clever Robots
<https://www.marginallyclever.com/>
Ph: +1 (604) 259-9564
Mo: +1 (604) 916-2281

**Comment by IDmedia** [comment]
I'll see if I can figure out where exactly the short is.
This is my first real Arduino project, so I guess I'll stick with the AMS 1 for now, but I'll gladly contribute patches if I get the version 2.3 to work!

Closing this issue now. Hopefully others will find this if they buy a cheap AMS 1 off eBay with a short. :)

**Comment by i-make-robots** [comment]
This is why I only support Marginally Clever made robots.  I test every
part and ship fully assembled so that any problems are not in the hardware.

On Mon, May 30, 2016 at 12:01 AM, IDmedia <notifications@github.com> wrote:

> I'll see if I can figure out where exactly the short is.
> This is my first real Arduino project, so I guess I'll stick with the AMS
> 1 for now, but I'll gladly contribute patches if I get the version 2.3 to
> work!
>
> Closing this issue now. Hopefully others will find this if they buy a
> cheap AMS 1 off eBay with a short. :)
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/MarginallyClever/Makelangelo-firmware/issues/7#issuecomment-222425084>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABZYhtWs70Y1XJ_l4nip0-oeJjWDaFAVks5qGotPgaJpZM4IpRMs>
> .
>



-- 
Dan Royer, Owner, Marginally Clever Robots
<https://www.marginallyclever.com/>
Ph: +1 (604) 259-9564
Mo: +1 (604) 916-2281
