### ISSUE TITLE
Case error in motor.cpp

### ISSUE THREAD

**Issue by captFuture** [MarginallyClever/Makelangelo-firmware#87]
After switching on VERBOSE mode in config.h the sketch complains about motorNames and motors not being defined.

### easy fix
correct case for the following part in motor.cpp line 675

/**
   Step one motor one time in the currently set direction.
   @input newx the destination x position
   @input newy the destination y position
 **/
void motor_onestep(int motor) {
#ifdef VERBOSE
  Serial.print(**MotorNames**[motor]);
#endif

  digitalWrite(**motors**[motor].step_pin, HIGH);
  digitalWrite(**motors**[motor].step_pin, LOW);
}

**Comment by i-make-robots** [comment]
Nice!  I don't remember the last time I used verbose.  It's kind of a crutch for me.  "this code is useful and I don't want to delete it and I don't want commented code everywhere..."
