### ISSUE TITLE
rename eeprom.h/.cpp to eeprom_wrapper.h/.cpp

### ISSUE THREAD

**Issue by cad435** [MarginallyClever/Makelangelo-firmware#92]
src/eeprom.h/.cpp defines a class named "Eeprom", whilst there is the class "EEPROM" from Arduino HAL. 

This works somehow with Arduino software but is directly agains c/cpp code guidelines as inclusions can be case insensitive. This results in massive compilation error when compiling with a standard gcc-compiler (in my case invoked via platformIO).

I'd suggest renaming the own header/src file to "eeprom_wrapper" to differenciate between classes as well as the associated class.

- cad435

**Comment by i-make-robots** [comment]
That sound great!  Send in a PR.

**Comment by cad435** [comment]
#93

**Comment by cad435** [comment]
Also, I can only suggest developing that project in PlatformIO...

This firmware is HUGE already, Arduino gets really messy at this point...

**Comment by i-make-robots** [comment]
Yes... arduino mega is about the only version that still runs the firmware.  We're looking at getting into platformio, which might be the moment we break away from arduino.  already have an SKR 1.4 on order and will probably have to make the switch then...

**Comment by cad435** [comment]
Ah yeah, Arduino did it again, the pull request you merged has some errors, because the arduino compiler cached to much files and gave me no errors... I corrected them all and will make a new pull request. 

Now it should all be working again (Restarting of the arduino IDE clears the cached files)
